### ISSUE TITLE
Prevent studies from being approved,  but not published

### ISSUE THREAD

**Issue by MattGMoz** [mozilla/delivery-console#284]
We've had this issue several times where a new study is created and approved. The people working on the study think they have published it, but it is not actually live. It normally takes a few days for us to realize the oversight and get the recipe actually published. Right now when someone asks for an approval on a recipe I go in and review it. I click approve then I have to go BACK down the breadcrumb trail to view the latest version before I see the publish button. This is not the behavior when you update a recipe. In that instance approval is publishing.

Some thoughts on how we could improve this:

- When you are editing a recipe it would be nice to make “live/not live” super visible in all views. 

- We could also make the publish button appear as soon as you’ve approved a version on that same page so I don’t have to backtrack to find it

- Add clearer feedback text after approving such as "Approved, but not published" for V1 of a recipe or "Approved and published" for V2+ of a recipe

--- 

- [x] Better notification message for approved-but-not-yet-published recipes [PR #681](https://github.com/mozilla/delivery-console/pull/681)
- [x] Display, in list of recipes, which recipes are approved but not published [PR #684](https://github.com/mozilla/delivery-console/pull/684)
- [x] Redirect back to recipe details page after approval [PR #688](https://github.com/mozilla/delivery-console/pull/688)

**Comment by jtg567** [comment]
>maybe a UI element, like a header or something (or stripes bordering it) would be red by default and only turn green when the study is active - something bigger than a button that you wouldn't necessarily need foveal vision for

**Comment by peterbe** [comment]
I incidentally improved the notification messages on the recipe details page in [this PR](https://github.com/mozilla/delivery-console/pull/681). 
In particular see [this comment](https://github.com/mozilla/delivery-console/pull/681#issuecomment-451275026). That *should* resolve the comment *"Add clearer feedback text after approving such as "Approved, but not published"* above.

The next changes I propose to make is to make it redirect back to the recipe details page after you have just approved it instead of staying on the approval request page. 
Also, the "Enrollment Active" column shouldn't say just "-- Disabled" for recipes that are approved but not published.

**Comment by peterbe** [comment]
Note-to-self; the internal functionality is about to change to change quite a lot as we move the to the v3 API. So any attempts I make should be blocked by that change and potentially "redone" to work with the new API.

**Comment by peterbe** [comment]
In https://github.com/mozilla/delivery-console/pull/684 we discuss the wording of the last column in the recipe listing page. For recipes that *are* approved but haven't been enabled yet it now stands out a little bit more. 

We have bigger plans with the columns but it's a bit more involved and that effort/discussion is going on in: https://github.com/mozilla/delivery-console/issues/573

**Comment by peterbe** [comment]
> Also, the "Enrollment Active" column shouldn't say just "-- Disabled" for recipes that are approved but not published.

To tackle that, see this PR: https://github.com/mozilla/delivery-console/pull/684

Next action to work on is...

> make it redirect back to the recipe details page after you have just approved it instead of staying on the approval request page.

**Comment by peterbe** [comment]
All sub-dependent tasks/pull requests are now closed. Yay!
